--------------------------------------------------------
--  Fichier créé - mercredi-janvier-06-2021   
--------------------------------------------------------
DROP SEQUENCE "ZEINEB"."COMMANDESVENTE_SEQ";
DROP TABLE "ZEINEB"."ARTICLE";
DROP TABLE "ZEINEB"."AVIS";
DROP TABLE "ZEINEB"."CLIENT";
DROP TABLE "ZEINEB"."COMMANDESACHAT";
DROP TABLE "ZEINEB"."COMMANDESVENTE";
DROP TABLE "ZEINEB"."FOURNISSEUR";
DROP TABLE "ZEINEB"."MACHINES";
DROP TABLE "ZEINEB"."PERSONNEL";
DROP TABLE "ZEINEB"."PLAT1";
DROP TABLE "ZEINEB"."POSTE";
DROP TABLE "ZEINEB"."PROGRAMME";
DROP TABLE "ZEINEB"."PROMOTION";
DROP TABLE "ZEINEB"."RECLAMATION";
--------------------------------------------------------
--  DDL for Sequence COMMANDESVENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ZEINEB"."COMMANDESVENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."ARTICLE" 
   (	"CODE" NUMBER, 
	"QUANTITE" NUMBER, 
	"PRIX" NUMBER, 
	"TYPE_AR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVIS
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."AVIS" 
   (	"ID_AVIS" NUMBER, 
	"DATE_AVIS" NUMBER, 
	"NB_ÉTOILES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(30 BYTE), 
	"PRENOM" VARCHAR2(30 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"POIDS" NUMBER, 
	"TAILLE" NUMBER, 
	"TEL" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDESACHAT
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."COMMANDESACHAT" 
   (	"TYPE" VARCHAR2(30 BYTE), 
	"QUANTITÉ" VARCHAR2(20 BYTE), 
	"NOMBRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDESVENTE
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."COMMANDESVENTE" 
   (	"ID_COMMANDESVENTE" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(30 BYTE), 
	"PRIX" NUMBER, 
	"DATE_FABRICATION" VARCHAR2(30 BYTE), 
	"QTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."FOURNISSEUR" 
   (	"NOM_SOCIETÉ" VARCHAR2(40 BYTE), 
	"NUMERO" NUMBER, 
	"MAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINES
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."MACHINES" 
   (	"MEALS" VARCHAR2(20 BYTE), 
	"POIDS_IDEAL" VARCHAR2(20 BYTE), 
	"DUREE_REGIME" VARCHAR2(20 BYTE), 
	"SPORT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."PERSONNEL" 
   (	"ID_PERSONNEL" NUMBER, 
	"NOMP" VARCHAR2(30 BYTE), 
	"PRENOMP" VARCHAR2(30 BYTE), 
	"DATE_NAISSANCE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"SALAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLAT1
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."PLAT1" 
   (	"NOMPLAT" VARCHAR2(20 BYTE), 
	"INGREDIENTS" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PAYMANT" VARCHAR2(20 BYTE), 
	"REF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POSTE
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."POSTE" 
   (	"ID_POSTE" NUMBER, 
	"NOMPOSTE" VARCHAR2(30 BYTE), 
	"SALAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROGRAMME
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."PROGRAMME" 
   (	"MEALS" VARCHAR2(30 BYTE), 
	"SPORT" VARCHAR2(30 BYTE), 
	"DUREE_REGIME" VARCHAR2(20 BYTE), 
	"POIDS_IDEAL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."PROMOTION" 
   (	"ID" NUMBER, 
	"POURCENTAGE" NUMBER, 
	"DELAI" NUMBER, 
	"DATE_PRO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "ZEINEB"."RECLAMATION" 
   (	"ID_RECLAMATION" NUMBER, 
	"DATER" NUMBER, 
	"NUM_RECLAMATION" NUMBER, 
	"OBJ_RECLAMATION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ZEINEB.ARTICLE
SET DEFINE OFF;
REM INSERTING into ZEINEB.AVIS
SET DEFINE OFF;
REM INSERTING into ZEINEB.CLIENT
SET DEFINE OFF;
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (9610,'mari','rosen','Femme',87,170,89678321,'mari@gmail.com',37);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (569,'zen','harak','femme',60,160,85646356,'zh_harak@gmail.com',18);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (9650,'bella','rosenberg','FEMME',75,170,89756423,'bella@gmail.com',28);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (9600,'Ali','Bougatfa','Homme',95,190,98357187,'Ali.Bo@gmail.com',23);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (9300,'Alex','Aran','FEMME',70,175,69354897,'Alex.Ar@gmail.com',20);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (11,'ara','beca','femme',110,167,8956789,'ara@gmail.com',27);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (9666,'mahdi','harakati','HOMME',100,192,56106345,'mahdi@espt.com',30);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (8637,'nada','ala','femme',85,175,56897654,'cutie@esprit.com',40);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (9635,'Ali','Boulabiar','70',167,96032584,90,'194',50);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (1235,'Alex','Ajax','Homme',153,190,98564721,'Alex@gmail.com',46);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (6020,'Zen','Haraka','Femme',80,173,97121266,'Zen@gmail.com',22);
Insert into ZEINEB.CLIENT (ID_CLIENT,NOM,PRENOM,GENDER,POIDS,TAILLE,TEL,EMAIL,AGE) values (5500,'amen','alex','homme',110,185,985236,'alumin@gmail.fr',27);
REM INSERTING into ZEINEB.COMMANDESACHAT
SET DEFINE OFF;
REM INSERTING into ZEINEB.COMMANDESVENTE
SET DEFINE OFF;
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (8006,'Lose Fat',500,'20 novembre 2020',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (8526,'keto2',180,'25/03/2019',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (78,'Programme',120,'20/07/2020',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (9002,'loseFat3',189,'20decembre',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (10,'ddd',15,'15',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (897,'KUKA',72,'23/03/2007',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (1961,'keto',155,'21/03/2020',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (6001,'Programme2',300,'20 decemre 2018',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (6002,'Keto Regime Proteine',275,'6 mai 2017',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (9001,'Keto Fat Regime',390,'27 juillet 2017',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (9350,'Regime 4 you',385,'06/04/2019',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (0,'sunshine',369,'9 mars 2020',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (3600,'VitaMAX',685,'3 mars 2019',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (3806,'VITA_Program',300,'2 janvier 2019',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (899999,'hope',357,'4 janvier 2021',null);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (9639,'Keto36',150,'02/04/2016',2);
Insert into ZEINEB.COMMANDESVENTE (ID_COMMANDESVENTE,NOM_PRODUIT,PRIX,DATE_FABRICATION,QTE) values (6936,'Keto96',2500,'02/09/2017',650);
REM INSERTING into ZEINEB.FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into ZEINEB.MACHINES
SET DEFINE OFF;
REM INSERTING into ZEINEB.PERSONNEL
SET DEFINE OFF;
REM INSERTING into ZEINEB.PLAT1
SET DEFINE OFF;
Insert into ZEINEB.PLAT1 (NOMPLAT,INGREDIENTS,ADRESSE,PAYMANT,REF) values ('Keto','Avocato','Ariana','180 dt',321698);
REM INSERTING into ZEINEB.POSTE
SET DEFINE OFF;
REM INSERTING into ZEINEB.PROGRAMME
SET DEFINE OFF;
REM INSERTING into ZEINEB.PROMOTION
SET DEFINE OFF;
REM INSERTING into ZEINEB.RECLAMATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."ARTICLE_PK" ON "ZEINEB"."ARTICLE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."AVIS_PK" ON "ZEINEB"."AVIS" ("ID_AVIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."CLIENT_PK" ON "ZEINEB"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDESACHAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."COMMANDESACHAT_PK" ON "ZEINEB"."COMMANDESACHAT" ("TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDESVENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."COMMANDESVENTE_PK" ON "ZEINEB"."COMMANDESVENTE" ("ID_COMMANDESVENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."FOURNISSEUR_PK" ON "ZEINEB"."FOURNISSEUR" ("NOM_SOCIETÉ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MACHINES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."MACHINES_PK" ON "ZEINEB"."MACHINES" ("MEALS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."PERSONNEL_PK" ON "ZEINEB"."PERSONNEL" ("ID_PERSONNEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PLAT1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."PLAT1_PK" ON "ZEINEB"."PLAT1" ("NOMPLAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POSTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."POSTE_PK" ON "ZEINEB"."POSTE" ("ID_POSTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROGRAMME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."PROGRAMME_PK" ON "ZEINEB"."PROGRAMME" ("MEALS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."PROMOTION_PK" ON "ZEINEB"."PROMOTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZEINEB"."RECLAMATION_PK" ON "ZEINEB"."RECLAMATION" ("ID_RECLAMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger COMMANDESVENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ZEINEB"."COMMANDESVENTE_TRG" 
BEFORE INSERT ON COMMANDESVENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ZEINEB"."COMMANDESVENTE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."ARTICLE" ADD CONSTRAINT "ARTICLE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."ARTICLE" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."ARTICLE" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVIS
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."AVIS" ADD CONSTRAINT "AVIS_PK" PRIMARY KEY ("ID_AVIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."AVIS" MODIFY ("DATE_AVIS" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."AVIS" MODIFY ("ID_AVIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."CLIENT" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."CLIENT" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."CLIENT" MODIFY ("TAILLE" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."CLIENT" MODIFY ("POIDS" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDESACHAT
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."COMMANDESACHAT" ADD CONSTRAINT "COMMANDESACHAT_PK" PRIMARY KEY ("TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."COMMANDESACHAT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."COMMANDESACHAT" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDESVENTE
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."COMMANDESVENTE" ADD CONSTRAINT "COMMANDESVENTE_PK" PRIMARY KEY ("ID_COMMANDESVENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."COMMANDESVENTE" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."COMMANDESVENTE" MODIFY ("ID_COMMANDESVENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("NOM_SOCIETÉ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."FOURNISSEUR" MODIFY ("NOM_SOCIETÉ" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."FOURNISSEUR" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MACHINES
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."MACHINES" ADD CONSTRAINT "MACHINES_PK" PRIMARY KEY ("MEALS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."MACHINES" MODIFY ("MEALS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."PERSONNEL" ADD CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("ID_PERSONNEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."PERSONNEL" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."PERSONNEL" MODIFY ("ID_PERSONNEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAT1
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."PLAT1" MODIFY ("PAYMANT" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."PLAT1" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."PLAT1" MODIFY ("INGREDIENTS" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."PLAT1" MODIFY ("NOMPLAT" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."PLAT1" ADD CONSTRAINT "PLAT1_PK" PRIMARY KEY ("NOMPLAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTE
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."POSTE" ADD CONSTRAINT "POSTE_PK" PRIMARY KEY ("ID_POSTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."POSTE" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."POSTE" MODIFY ("ID_POSTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROGRAMME
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."PROGRAMME" ADD CONSTRAINT "PROGRAMME_PK" PRIMARY KEY ("MEALS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."PROGRAMME" MODIFY ("MEALS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."PROMOTION" ADD CONSTRAINT "PROMOTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."PROMOTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "ZEINEB"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("ID_RECLAMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ZEINEB"."RECLAMATION" MODIFY ("NUM_RECLAMATION" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."RECLAMATION" MODIFY ("DATER" NOT NULL ENABLE);
  ALTER TABLE "ZEINEB"."RECLAMATION" MODIFY ("ID_RECLAMATION" NOT NULL ENABLE);
